sudo: false
language:
    - cpp

compiler:
    - gcc
    - clang

env:
    - BOOST_VER=1.54.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.54.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.54.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.54.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.55.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.55.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.55.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.55.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.56.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.56.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.56.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.56.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.57.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.57.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
    - BOOST_VER=1.57.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
    - BOOST_VER=1.57.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"

before_install:
    - git clone --recursive https://github.com/boostorg/boost.git ../boost_${BOOST_VER//./_}
    - cd ../boost_${BOOST_VER//./_}
    - git checkout boost-${BOOST_VER}
    - cd -
    - export BOOST_ROOT=$TRAVIS_BUILD_DIR/../boost_${BOOST_VER//./_}

install:
    - cd $BOOST_ROOT
    - ./bootstrap.sh --with-toolset=$CC
    - ./b2 headers
    - ./b2 --stagedir=.
    - cd -

cache:
    directories:
      - $BOOST_ROOT

script:
    - mkdir ../build
    - cd ../build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
            $TRAVIS_BUILD_DIR
    - make
    - make test

after_failure:
    - cat Testing/Temporary/LastTest.log 
